title: martin cronjÃ©
email: martin@cron.je
description: >- # this means to ignore newlines until "baseurl:"
  My experiences in leading, building and transforming teams to deliver well-crafted software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://martincronje.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: martincronje
github_username:  martincronje

# Build settings
theme: minima
#remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
